spring.application.name=api-clientes

server.port=8081

database.host=jdbc:postgresql://localhost:5432/bdclientes
database.user=postgres
database.pass=coti

cors.allowed=http://localhost:4200,http://localhost:3000